### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by bebehei** [FlorianLudwig/rsnapshotfs#1]
Hi, without python-knowledge and looking over the code, is this usable?

**Comment by FlorianLudwig** [comment]
The project never made it past the experimental stage.  But I added a quick README https://github.com/FlorianLudwig/rsnapshotfs/blob/master/README.rst maybe it helps?

**Comment by FlorianLudwig** [comment]
@bebehei did the readme help you?  Did you find the code to be useful for you in some way?

**Comment by bebehei** [comment]
Yes, indeed. The readme helped. Maybe I'll feature this on the rsnapshot.org website.

But TBH, personally I have no use-case for this. The classical `find` did always work for me.
